adding signin page to Front-End-Projects
TusharKesarwani/Front-End-Projects pull request #111
Opened 2023-01-07 16:28 UTC by himanshu240601

pr for adding signin page

2023-01-07 22:24 UTC, TusharKesarwani commented on Projects/SignIn Page/README.md
> +Inspiration - [Dribble Design Link](https://dribbble.com/shots/18063206-Login-UI?utm_source=Clipboard_Shot&utm_campaign=D-studio&utm_content=Login%20UI&utm_medium=Social_Share&utm_source=Clipboard_Sh
Remove this

2023-01-08 04:16 UTC, himanshu240601 commented on Projects/SignIn Page/README.md
> +Inspiration - [Dribble Design Link](https://dribbble.com/shots/18063206-Login-UI?utm_source=Clipboard_Shot&utm_campaign=D-studio&utm_content=Login%20UI&utm_medium=Social_Share&utm_source=Clipboard_Sh
Removed README.md

2023-01-08 18:13 UTC, Vanshiii203 requested changes
Your project is not showing in deploy version
Please fix that and link your PR with the issue

2023-01-08 20:47 UTC, TusharKesarwani approved these changes

2023-01-08 20:47 UTC, merged