Added Age calculator
TusharKesarwani/Front-End-Projects pull request #1169
Opened 2023-06-11 16:42 UTC by ANI2707

## 🛠️ Issue (Number)
 Issue No #958

# Description
I have added an Age calculator according to the issue mentioned .this age calculator calculates a person's age according to their birth date. In output it gives **You are 0 years, 0 months and 9 days old**. Below I have attached some SS to found it helpful. Thank you!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] I have made this from my own
- [x] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot 2023-06-04 193752](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/a34e2c3f-4b2c-492d-b17d-b9981e424605)
![Screenshot (224)](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/7acd0013-cf4f-44a3-b7bf-7e0609f8ba2b)
![Screenshot 2023-06-04 193921](https://github.com/TusharKesarwani/Front-End-Projects/assets/108017771/c83e6687-c9bd-4cc9-8702-29b9b4a1b45c)

2023-06-16 12:46 UTC, ANI2707 commented
@harshit-paneri can you please review my PR?

2023-06-20 12:16 UTC, ANI2707 commented
Please review my PR @zugzwang03 and @TusharKesarwani

2023-06-21 06:01 UTC, zugzwang03 requested changes
add README.md file

2023-07-03 13:06 UTC, zugzwang03 approved these changes

2023-07-04 10:31 UTC, TusharKesarwani approved these changes

2023-07-04 10:31 UTC, merged