Add LinkedIn Like button component
TusharKesarwani/Front-End-Projects pull request #1318
Opened 2023-06-19 14:17 UTC by Ayush9951

close #1260 
Hi @zugzwang03, I've successfully created a clone of LinkedIn like button component, please consider merging my pull request with the main branch.

![Screenshot 2023-06-19 194606](https://github.com/TusharKesarwani/Front-End-Projects/assets/60573378/d42f7f81-8bf7-4352-9670-87bfd511d469)

2023-06-20 05:08 UTC, zugzwang03 requested changes
make a README.md file as well

2023-06-21 05:59 UTC, zugzwang03 approved these changes

2023-06-22 20:03 UTC, TusharKesarwani commented
This is not a project

2023-06-22 20:03 UTC, closed without merging

2023-06-23 04:49 UTC, Ayush9951 commented
> This is not a project

well this the kind of task that companies can give during front end  interviews if you don't know about it