added _twitter_clone
TusharKesarwani/Front-End-Projects pull request #1345
Opened 2023-06-20 07:50 UTC by kritika2313

## 🛠️ Issue (1280)

Closes # 1280

# Description
Added a twitter clone project .Used tech stack are:

- HTML
- CSS

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
file:///c%3A/Users/warri/Front-End-Projects/Projects/Twitter_clone/index.html

![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/92994108/94d03f3a-2417-4ccd-90c5-ed58e5331dc1)

2023-06-21 06:32 UTC, zugzwang03 requested changes
add README.md file

2023-06-21 07:12 UTC, kritika2313 commented
> add README.md file

i have updated this pr with readme file pls have a look.

2023-06-22 04:42 UTC, zugzwang03 approved these changes

2023-06-22 19:20 UTC, TusharKesarwani approved these changes

2023-06-22 19:21 UTC, merged