Added ReadMe file to the Cafe Website project
TusharKesarwani/Front-End-Projects pull request #1377
Opened 2023-06-21 07:15 UTC by krutika-ladani

## 🛠️ Issue (#1374)

Closes #1374

# Description

Added ReadMe.md file to the Cafe Website project.

# Checklist:

- [x] I have made this from my own
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

![Screenshot (57)](https://github.com/TusharKesarwani/Front-End-Projects/assets/119760273/6f7a6fce-b9f2-451f-bb54-0fd84addbc5e)

2023-06-21 07:16 UTC, krutika-ladani commented
@zugzwang03 please approve my pull request

2023-06-22 04:35 UTC, zugzwang03 approved these changes

2023-06-22 04:36 UTC, zugzwang03 requested changes
Why did you also include readme of BMICalculator here?

2023-06-22 12:25 UTC, krutika-ladani commented
@zugzwang03 I have made the necessary updates. please check it again and let me know If I need to make any further changes.

2023-06-22 20:49 UTC, closed without merging