Add Frequently Asked Questions component
TusharKesarwani/Front-End-Projects pull request #1465
Opened 2023-06-24 18:02 UTC by Ayush9951

close #1405 
Hi @zugzwang03, I've created a clone of frequently asked questions component of ssoc website
user can click on question to display answer.

![Screenshot 2023-06-24 233200](https://github.com/TusharKesarwani/Front-End-Projects/assets/60573378/118b5ddb-ed13-4efd-8f45-d50eafe7be34)

2023-06-25 05:46 UTC, zugzwang03 approved these changes

2023-06-27 12:45 UTC, zugzwang03 approved these changes

2023-06-27 12:46 UTC, zugzwang03 requested changes
add readme file

2023-06-28 04:18 UTC, zugzwang03 approved these changes

2023-07-04 10:54 UTC, TusharKesarwani approved these changes

2023-07-04 10:54 UTC, merged