Updated Code of  #1007
TusharKesarwani/Front-End-Projects pull request #1520
Opened 2023-06-28 19:28 UTC by codingwithveer18

## 🛠️ Issue #1007 

# Description

Code for my project i.e regarding Mental Health Awareness Initiative.

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

-I have performed a self-review of my own code
-I have commented my code, particularly in hard-to-understand areas
-I have made corresponding changes to the documentation
-My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://soulboundconfessions.netlify.app/
![Screenshot 2023-06-29 003643](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/f59e6d4c-8670-48e4-8048-d3a9e0023f58)
![Screenshot 2023-06-29 003701](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/50bc5c29-5a1c-41c9-b5a5-005f68e73efe)
![Screenshot 2023-06-29 003713](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/e0419105-aa9e-4205-9409-274afcb7e235)
![Screenshot 2023-06-29 003724](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/a103dbe0-bb43-48d7-98bb-4cb3d004e132)
![Screenshot 2023-06-29 003733](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/751f9de0-f770-41b9-bed7-6326250e85e6)
![Screenshot 2023-06-29 003743](https://github.com/codingwithveer18/Front-End-Projects/assets/112725639/f651e1cf-2bfc-4ab0-8197-7572fee14817)

2023-06-29 04:35 UTC, harshit-paneri requested changes
File path is wrong
Your file path : /Soulbound_Confession/
correct file path  : /Projects/Soulbound_Confession/

2023-06-29 07:16 UTC, codingwithveer18 commented
Changes Done . Please Review

2023-06-29 07:26 UTC, harshit-paneri commented
Did you make figma

2023-06-29 07:36 UTC, codingwithveer18 commented
> Did you make figma

Yes , for the app ui , i made a figma prototype

2023-07-02 12:01 UTC, codingwithveer18 commented
@harshit-paneri  
Sir , Are there any more changes that to be made ?

2023-07-06 08:51 UTC, codingwithveer18 commented
That app.html file is just for the prototype.
main file is index one.
Is there anything to be checked sir @harshit-paneri

2023-07-06 08:53 UTC, codingwithveer18 commented
Also, my issue is not showing in Front-End Projects (under projects section on github).

2023-07-08 09:57 UTC, codingwithveer18 reviewed
minor changes

2023-07-14 11:13 UTC, TusharKesarwani requested changes
Revert changes in index.html file

2023-07-14 11:16 UTC, codingwithveer18 commented
> Revert changes in index.html file

Delete the path of the deleted file ,
Which was a figma prototype .
So do i have to add that again ?

2023-07-14 11:23 UTC, TusharKesarwani commented
> > Revert changes in index.html file
> 
> Delete the path of the deleted file , Which was a figma prototype . So do i have to add that again ?

You should revert changes made in the main index.html file

2023-07-14 12:25 UTC, codingwithveer18 commented
> > > Revert changes in index.html file
> > 
> > Delete the path of the deleted file , Which was a figma prototype . So do i have to add that again ?
> 
> You should revert changes made in the main index.html file

Done sir

2023-07-14 12:40 UTC, TusharKesarwani commented on index.html
Revert this file

2023-07-14 12:54 UTC, codingwithveer18 commented on index.html
Now okay sir ?

2023-07-15 15:19 UTC, codingwithveer18 commented
Changes Done . Please look into that

2023-07-16 07:34 UTC, TusharKesarwani requested changes
Do not add bootstrap files in folder
Connect them through link

2023-07-17 19:51 UTC, codingwithveer18 commented
Please look into this

2023-07-18 20:28 UTC, TusharKesarwani requested changes
Remove font awesome files and connect them remotely like Bootstrap

2023-07-19 14:53 UTC, codingwithveer18 commented
> Remove font awesome files and connect them remotely like Bootstrap

I'm unaware about this. I am not able to convert them remotely.

2023-07-20 19:51 UTC, TusharKesarwani commented
> > Remove font awesome files and connect them remotely like Bootstrap
> 
> I'm unaware about this. I am not able to convert them remotely.

Go to their website or search it on youtube

2023-07-21 11:43 UTC, codingwithveer18 commented
> > > Remove font awesome files and connect them remotely like Bootstrap
> > 
> > 
> > I'm unaware about this. I am not able to convert them remotely.
> 
> Go to their website or search it on youtube

Done Sir

2023-07-21 12:34 UTC, TusharKesarwani approved these changes

2023-07-21 12:36 UTC, TusharKesarwani requested changes
![Screenshot](https://github.com/TusharKesarwani/Front-End-Projects/assets/92527686/756405e2-4dce-49a0-81c4-d536f2438a0f)
Make it responsive

2023-07-22 11:00 UTC, TusharKesarwani requested changes
![Screenshot (1)](https://github.com/TusharKesarwani/Front-End-Projects/assets/92527686/339c7096-80f0-4815-83d0-b63989fa305a)

Make it responsive

2023-07-24 14:56 UTC, TusharKesarwani approved these changes

2023-07-24 14:57 UTC, merged