Hex code
TusharKesarwani/Front-End-Projects pull request #174
Opened 2023-01-09 19:41 UTC by MridulGupta007

HEX CODE GENERATOR

Creates random color codes and also provides their respective CSS Code which can be pasted in the CSS file.
Has a reset button to restore default color( white ).

2023-01-09 19:44 UTC, Rishikavishnoi commented
@MridulGupta007 mention issue no. and add a screenshot  of your project in the README.md file

2023-01-09 20:06 UTC, MridulGupta007 commented on Projects/Hex Code Generator/Readme.md
> +
![Screenshot (222)](https://user-images.githubusercontent.com/110561701/211398023-3b02d564-7aa9-4f0e-8f75-2210f647cf37.png)

2023-01-10 08:36 UTC, Vanshiii203 requested changes
@MridulGupta007 Attach a screenshot of your project in the Readme.md file and do not mention the issue in the readme file, link it with the PR (by using #issuenumber)

2023-01-10 21:16 UTC, MridulGupta007 commented
closes Issue #174

2023-01-10 23:05 UTC, MridulGupta007 commented
![Screenshot (222)](https://user-images.githubusercontent.com/110561701/211680833-4f6044e7-8750-401b-8a28-31642c5f42fc.png)

2023-01-11 05:42 UTC, Vanshiii203 commented
@MridulGupta007 Please remove the issue number from readme.md file

2023-01-11 08:37 UTC, MridulGupta007 commented
Done

2023-01-11 08:43 UTC, Vanshiii203 approved these changes

2023-01-11 16:23 UTC, merged