Finance
TusharKesarwani/Front-End-Projects pull request #1750
Opened 2023-07-15 13:48 UTC by AMRIT456

## 🛠️ Issue (Number) 887

Closes #887 

# Description
I have fixed the bug and the project is running smoothely.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/7dbb32e7-edc0-4a01-a630-106aa5b85df7)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/20245f1b-30ac-40d7-8ed7-79202bdf7d3a)

2023-07-16 06:15 UTC, harshit-paneri approved these changes

2023-07-21 12:52 UTC, TusharKesarwani requested changes
Make it responsive

2023-07-21 14:28 UTC, AMRIT456 commented
i had made the webpage responsive please review it.
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/3bd0e0fc-4d34-41bc-9a06-6d7d7464102a)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/67870234/470c07a7-a8a4-4c64-b8a3-83271146eab2)
above screenshots are of mobile screen

2023-07-23 12:00 UTC, TusharKesarwani commented
![Screenshot (2)](https://github.com/TusharKesarwani/Front-End-Projects/assets/92527686/ed8e8c08-892d-40e3-a396-716fa75118d8)
Make it responsive for all devices

2023-07-30 07:16 UTC, TusharKesarwani approved these changes

2023-07-30 07:17 UTC, merged