index.html
TusharKesarwani/Front-End-Projects pull request #1827
Opened 2023-07-24 16:38 UTC by harshsinghcs

this an animation wallpaper i  made

## 🛠️ Issue (Number)

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2023-07-24 17:05 UTC, harshsinghcs commented
I have made the Pull request please approve it @zugzwang03  @TusharKesarwani  @harshit-paneri

2023-07-25 13:15 UTC, harshsinghcs commented
> Issue number?

https://github.com/TusharKesarwani/Front-End-Projects/issues/1842

2023-07-26 03:43 UTC, zugzwang03 requested changes

2023-07-26 03:43 UTC, zugzwang03 commented on Projects/Animated-Wallpaper/colourfull.png
Where did you use this image?

2023-07-26 03:43 UTC, zugzwang03 commented on Projects/Animated-Wallpaper/oranges.jpg
Where did you use this image?

2023-07-27 07:50 UTC, zugzwang03 commented
Give the user options to change text and background, otherwise its use case reduces to huge extent

2023-07-27 17:10 UTC, harshsinghcs commented
> Give the user options to change text and background, otherwise its use case reduces to huge extent

now user have the option to change the text, color and image too

2023-07-27 17:11 UTC, harshsinghcs commented
now kindly review my pr and marge it🙏

2023-07-29 05:07 UTC, zugzwang03 approved these changes

2023-07-30 09:21 UTC, TusharKesarwani approved these changes

2023-07-30 09:21 UTC, merged