Text analyzer
TusharKesarwani/Front-End-Projects pull request #1856
Opened 2023-07-27 12:01 UTC by Ahasasjain

## 🛠️ Issue (Number)

Closes #1824 

# Description

Successfully Added Online Text Analyzer Project

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![LM-TextAnalyzer](https://github.com/TusharKesarwani/Front-End-Projects/assets/101923456/722f51b9-cff5-4443-9f93-fc0b6ee90080)

![DM-TextAnalyzer](https://github.com/TusharKesarwani/Front-End-Projects/assets/101923456/9bd7d12f-57fb-4aee-80f5-a6f8354d0c86)

![Example-TextAnalyzer](https://github.com/TusharKesarwani/Front-End-Projects/assets/101923456/96676061-09d8-454c-9b5e-6b6abbf1585d)

# DEPLOYMENT LINK
https://online-text-analyzer.netlify.app/

2023-07-27 12:04 UTC, Ahasasjain commented
@zugzwang03 @TusharKesarwani Please Review and merge my project - Online Text Analyzer.

2023-07-29 05:05 UTC, zugzwang03 approved these changes

2023-07-30 04:32 UTC, zugzwang03 approved these changes

2023-07-30 04:34 UTC, zugzwang03 requested changes
wait a minute
This is a React Project
React Projects aren't allowed

2023-07-30 09:32 UTC, closed without merging

2023-07-30 16:06 UTC, Ahasasjain commented
> wait a minute This is a React Project React Projects aren't allowed

Okay, But there are many React Projects already merged in the main branch