A talking Chatbot
TusharKesarwani/Front-End-Projects pull request #197
Opened 2023-01-11 14:32 UTC by alisha722

#172 Talking chatbot using html , css and js which can do normal day to day coversation.
![chat](https://user-images.githubusercontent.com/84632701/211819721-57748bba-30f8-458e-b7bb-215c988191d0.png)

2023-01-11 14:47 UTC, Vanshiii203 requested changes
Please remove the files of Age calculator

2023-01-11 15:03 UTC, alisha722 commented
> Please remove the files of Age calculator. Everything else looks fantastic! great job

yes deleted it . Have a check please .Thankyou so much !!

2023-01-11 15:10 UTC, Vanshiii203 approved these changes

2023-01-11 18:04 UTC, Rishikavishnoi approved these changes

2023-01-12 14:02 UTC, TusharKesarwani approved these changes

2023-01-12 14:02 UTC, merged