Add Rock paper scsissors game
TusharKesarwani/Front-End-Projects pull request #1976
Opened 2024-01-16 16:11 UTC by nguyenkhoi2806

# Description

This is a simple Rock Paper Scissors game implemented in JavaScript, HTML, and CSS. The game allows a user to play against the computer by choosing between Rock, Paper, and Scissors. The winner is determined based on the classic rules of the game.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality) 

# Checklist:

- [x] I have made this from my own 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot 2024-01-16 at 23 17 53](https://github.com/TusharKesarwani/Front-End-Projects/assets/16773113/c2a75e00-8abb-4497-9759-9829c66c6003)

2024-01-18 17:55 UTC, Hunter-420 commented on Projects/RockPaperScsissors/index.html
> +              <img src="./assets/svg/icon-paper.svg" class="m-auto" />
It would be beneficial to include descriptive alt attributes for all images

2024-01-18 17:56 UTC, Hunter-420 commented on Projects/RockPaperScsissors/index.html
> +            <span class="text:xl md:text-2xl font-bold text-white"
Ensure consistency in class naming conventions. For example, use either text:xl or text-xl

2024-01-18 18:03 UTC, Hunter-420 requested changes
I've reviewed the changes, and overall, the implementation is looking good. I gave you a couple of suggestions for further enhancement.

2024-01-19 00:09 UTC, nguyenkhoi2806 commented on Projects/RockPaperScsissors/index.html
> +            <span class="text:xl md:text-2xl font-bold text-white"
what is your suggestion change in this case

2024-01-19 02:59 UTC, nguyenkhoi2806 commented on Projects/RockPaperScsissors/index.html
> +            <span class="text:xl md:text-2xl font-bold text-white"
updated

2024-01-19 03:00 UTC, nguyenkhoi2806 commented on Projects/RockPaperScsissors/index.html
> +              <img src="./assets/svg/icon-paper.svg" class="m-auto" />
updated

2024-01-19 03:00 UTC, nguyenkhoi2806 commented
> I've reviewed the changes, and overall, the implementation is looking good. I gave you a couple of suggestions for further enhancement.

I updated please merge it

2024-01-19 04:41 UTC, Hunter-420 approved these changes

2024-01-19 04:42 UTC, Hunter-420 approved these changes

2024-01-29 14:50 UTC, TusharKesarwani approved these changes

2024-01-29 14:50 UTC, merged