Added Medcare Landing Page Project
TusharKesarwani/Front-End-Projects pull request #1979
Opened 2024-02-02 07:28 UTC by DineshK3012

## 🛠️ Issue (Number)

Closes #1971

# Description
This project is a demonstration of the landing page of a hospital website. The project is beginner-friendly made with html, css, bootstrap and js. The project is also fully responsive for any kind of device.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87605928/88caf78b-3886-4131-a3aa-98fcd1dff460)
![image](https://github.com/TusharKesarwani/Front-End-Projects/assets/87605928/bd5ed94f-0785-43d8-a0b9-626170e19cc3)

2024-03-11 17:17 UTC, TusharKesarwani requested changes
Make it responsive

2024-05-02 07:21 UTC, MuGrahiman commented
is this closed or not. can i contribute

2024-05-02 07:23 UTC, MuGrahiman commented
Could you please let me know if the issue is still ongoing or if it has been closed? I am interested in contributing to this open source project. Thank you.

2024-05-02 07:27 UTC, DineshK3012 commented
> Could you please let me know if the issue is still ongoing or if it has been closed? I am interested in contributing to this open source project. Thank you.

The issue is still open. You can contribute.

2025-04-06 08:14 UTC, closed without merging