GYM WEB
TusharKesarwani/Front-End-Projects pull request #202
Opened 2023-01-11 15:49 UTC by heyhimansh

#173 
Web <a href="https://gleaming-crepe-169406.netlify.app/" target ="_blank">Link</a>

![Gym Website (2)](https://user-images.githubusercontent.com/72097380/211876522-19203c57-5421-4654-b577-a910367ffda7.png)

2023-01-11 16:36 UTC, zugzwang03 commented
> #173

Kindly put in some screenshots of your website, so that we can understand its working.

2023-01-12 06:04 UTC, Vanshiii203 requested changes
Great job! But please add a readme.md file

2023-01-12 06:37 UTC, Vanshiii203 commented
> README.md file added

please add a screenshot of project to the readme.md file

2023-01-12 15:52 UTC, Vanshiii203 approved these changes

2023-01-14 10:39 UTC, TusharKesarwani approved these changes

2023-01-14 10:39 UTC, merged