Developer profile branch
TusharKesarwani/Front-End-Projects pull request #210
Opened 2023-01-12 05:56 UTC by monishkajha17

2023-01-12 06:34 UTC, Rishikavishnoi requested changes
@monishkajha17 add a screenshot of your project in the README.md file

2023-01-12 07:28 UTC, monishkajha17 commented
@Rishikavishnoi okay done please check

2023-01-13 18:23 UTC, monishkajha17 commented
Is this PR is ready to merge or it still have problems. Kindly confirm

2023-01-14 06:24 UTC, Vanshiii203 approved these changes

2023-01-16 05:35 UTC, monishkajha17 commented
When this PR will be merged?

2023-01-17 21:11 UTC, TusharKesarwani commented on Projects/Developer  Profile card/index.html
> +            <img src="C:\Users\Monishka jha\Desktop\WhatsApp Image 2022-11-21 at 00.55.42.jpg" height="100" width="100" alt="profile">
Add required files and change the link according to that file

2023-01-18 04:28 UTC, monishkajha17 commented
@TusharKesarwani Pls check

2023-01-18 20:27 UTC, TusharKesarwani commented
![Screenshot](https://user-images.githubusercontent.com/92527686/213287442-3871499a-7ee4-462a-9c95-547bc2fdf1bb.png)
@monishkajha17 
The image is not visible

2023-01-19 07:13 UTC, monishkajha17 commented
@TusharKesarwani  Can I just make the image into link because its not working in folder

2023-01-19 07:22 UTC, monishkajha17 commented
@TusharKesarwani I just updated a image kindly check

2023-01-19 14:25 UTC, TusharKesarwani commented
![Screenshot](https://user-images.githubusercontent.com/92527686/213467331-7fbafef3-64ff-44d6-990d-fa02b2f8f3c5.png)
Icons are still not working
@monishkajha17

2023-01-20 06:01 UTC, monishkajha17 commented
@TusharKesarwani  Kindly check now I have fixed the icons

2023-01-21 09:30 UTC, TusharKesarwani approved these changes

2023-01-21 09:30 UTC, merged