Audio_to_text conversion
TusharKesarwani/Front-End-Projects pull request #356
Opened 2023-01-20 10:13 UTC by Amit0412

## 🛠️ Issue (Number)

Closes #350 

# Description

It is the application which basically listens the audio that we speak and then converts it into or displays it in Hindi language. It is simply English to Hindi speech conversion. It is built by me and it is fully based on Html and JavaScript.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✔ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [✔] I have made this from my own
- [✔] I have taken help from some online recourses 
- [✔] My code follows the style guidelines of this project
- [✔] I have performed a self-review of my own code
- [✔] I have commented my code, particularly in hard-to-understand areas
- [✔ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Speech to Text Converter (हिंदी) - Google Chrome 1_20_2023 3_42_40 PM](https://user-images.githubusercontent.com/59620280/213670620-e2ec16bd-8ffc-40ae-b317-1a799dbf5b0a.png)

2023-01-20 13:02 UTC, Vanshiii203 requested changes
Please add a Readme.md file for your project

2023-01-20 13:45 UTC, Amit0412 commented
Mam I have done the changes which was requested by you. Kindly please see it and merge the PR.Thankyou

2023-01-20 14:05 UTC, Vanshiii203 approved these changes
LGTM!

2023-01-21 09:38 UTC, Rishikavishnoi approved these changes

2023-01-21 10:11 UTC, TusharKesarwani approved these changes

2023-01-21 10:11 UTC, merged