Add Quote Generator
TusharKesarwani/Front-End-Projects pull request #372
Opened 2023-01-21 09:40 UTC by harsitagarwalla187

## 🛠️ Closes Issue #137 

# Description

Added Quote Generator to the Projects.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2023-01-21 09:50 UTC, Rishikavishnoi requested changes
@harsitagarwalla187 add README.md file to describe your project ...!

2023-01-28 09:56 UTC, Vanshiii203 requested changes
add the screenshot of project in Readme.md file

2023-01-30 03:13 UTC, harsitagarwalla187 commented
@Vanshiii203 Please have a look.

2023-02-01 12:57 UTC, TusharKesarwani approved these changes

2023-02-01 12:57 UTC, merged