added Emoji Rating project
TusharKesarwani/Front-End-Projects pull request #410
Opened 2023-01-23 07:53 UTC by DeepanshiShimar

## 🛠️ Issue (Number)

Closes #393

# Description

Emoji Rating is an application  made from Html,Css and Js .People process and express themselves better with images than with plain text, as they offer a way to convey nuances and emotion. It can  be used to determine how  someone feels about your product or service.        

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://user-images.githubusercontent.com/103559339/213987618-157bc614-554e-4148-a0bb-a636d97fd50f.png)

2023-01-23 08:36 UTC, siddhi-244 requested changes
Please add a Readme for this project

2023-01-23 15:48 UTC, Rishikavishnoi requested changes
@DeepanshiShimar  add a README.md file to explain your project.

2023-01-24 08:06 UTC, DeepanshiShimar commented
Added a readme file
Please merge my pull request

2023-01-25 15:18 UTC, Vanshiii203 approved these changes

2023-01-25 15:19 UTC, siddhi-244 approved these changes

2023-01-26 12:39 UTC, TusharKesarwani approved these changes

2023-01-26 12:40 UTC, merged