Added Gooey cursor
TusharKesarwani/Front-End-Projects pull request #436
Opened 2023-01-24 12:44 UTC by khushigarg1

## 🛠️ Issue (Number)

Closes #363 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2023-01-25 09:58 UTC, LiQuiD-404 requested changes
@khushigarg1 Kindly add a demo video showcasing your project.

2023-01-25 13:53 UTC, khushigarg1 commented
> @khushigarg1 Kindly add a demo video showcasing your project.

https://www.veed.io/view/d199ed99-ac4f-4ad3-8501-aee7473980e4?source=compressor-sharing

2023-01-25 15:27 UTC, Vanshiii203 approved these changes

2023-01-26 12:48 UTC, TusharKesarwani approved these changes

2023-01-26 12:48 UTC, merged