Blog Website
TusharKesarwani/Front-End-Projects pull request #468
Opened 2023-01-26 20:02 UTC by aryaman1202

🛠️ Issue (Number) = #333

Closes #333 

# Description

I have made a Blog Website and the screenshot of the same has been attached for your kind reference. Please approve and merge my issue. Any suggestions will be welcome.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![blog-project](https://user-images.githubusercontent.com/91802408/214937314-d1207850-093a-44ec-80fd-941916294c6c.jpeg)

2023-01-27 05:06 UTC, Vanshiii203 requested changes
make the navbar and home page responsive.

2023-01-29 10:44 UTC, aryaman1202 commented
> make the navbar and home page responsive.

![mob-1](https://user-images.githubusercontent.com/91802408/215320860-6f86ff5c-b773-4dcd-a42c-256c19b71cde.jpeg)
![mob-2](https://user-images.githubusercontent.com/91802408/215320864-e5a12b3a-7deb-411d-92b0-0e12020f30e5.jpeg)

@Vanshiii203 Ma'am this is the mobile layout of the website and the website code already includes media queries so the navbar and website layout is responsive. The screenshot above is layout of website on mobile interface. Please see to it. Thank you so much ma'am.

2023-01-30 07:21 UTC, aryaman1202 commented
@TusharKesarwani Please kindly look into it and merge it.

2023-01-30 15:34 UTC, TusharKesarwani approved these changes

2023-01-30 15:35 UTC, merged