Maze Game
TusharKesarwani/Front-End-Projects pull request #541
Opened 2023-01-30 19:00 UTC by khushigarg1

## 🛠️ Issue (Number)
#536 

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2023-01-31 13:05 UTC, Vanshiii203 requested changes
add a readme.md file for your project

2023-02-01 13:31 UTC, zugzwang03 requested changes
images are not visible in the readme file

2023-02-07 14:34 UTC, Arun9739 requested changes
Create a separate image folder for images and put all image over there.

2023-02-13 19:26 UTC, closed without merging

2023-07-05 02:01 UTC, wokla23006 commented on Projects/maze Game/index.html
> +  <head>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2270952767365068"
     crossorigin="anonymous"></script>

2023-07-05 02:03 UTC, wokla23006 commented on Projects/maze Game/index.html
> +    <!-- <link rel="stylesheet" href="css/index.css" /> -->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2270952767365068" crossorigin="anonymous"></script>