Movie Data Base
TusharKesarwani/Front-End-Projects pull request #542
Opened 2023-01-30 19:19 UTC by vimarsh11

## 🛠️ Issue #239

Closes #239

# Description
I have created a Movie Data Base using HTML, CSS, JS.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x
![Screenshot 2023-01-31 004839](https://user-images.githubusercontent.com/104987339/215573909-7f2213ff-c544-485c-afb7-db62a53b9f95.png)
] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2023-01-31 06:54 UTC, harshit-paneri requested changes
Amazing website, but for approved please  create Readme also

2023-01-31 08:06 UTC, harshit-paneri approved these changes

2023-01-31 08:07 UTC, vimarsh11 commented
@harshit-paneri  README file added .

2023-02-04 04:41 UTC, Vanshiii203 approved these changes

2023-02-04 10:54 UTC, TusharKesarwani approved these changes

2023-02-04 10:55 UTC, merged