Modern credi Card form Webpage
TusharKesarwani/Front-End-Projects pull request #602
Opened 2023-02-09 19:16 UTC by ashadmuneer

## 🛠️ Issue (Number)

Closes #558 

# Description

Modern credit Card form Webpage design by using Html,Css & java Script.it is very Intractive and fully responsive.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
link https://credit-card-details.ashadmuneer.repl.co/

2023-02-10 05:14 UTC, harsh5902 commented
add a readme file

2023-02-10 05:17 UTC, harsh5902 requested changes
Add a Readme file.

2023-02-11 10:10 UTC, ashadmuneer commented
@harsh5902  @Vanshiii203  @TusharKesarwani  

readme added done

2023-02-11 11:02 UTC, harsh5902 approved these changes

2023-02-12 20:19 UTC, TusharKesarwani approved these changes

2023-02-12 20:19 UTC, merged