Adding Javascript Piano
TusharKesarwani/Front-End-Projects pull request #623
Opened 2023-02-12 14:30 UTC by Bishal011

## 🛠️ Issue (#616)

Closes #616 

# Description

This project is made by using HTML, CSS and JAVASCRIPT.
We Use HTML For Creating A Structure For The Piano Keyboard.
Styling Using CSS, Giving The Piano Effect On Buttons, And Did The Same Color Of The Piano Using Css.
Lastly, We Use JavaScript For Piano Keyboard Sound Play Functionality.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

video -- 

https://user-images.githubusercontent.com/105370000/218316463-d14ac0d4-3abc-4068-b2a8-1b9386e51c52.mp4

Screenshots--

![Screenshot (214)](https://user-images.githubusercontent.com/105370000/218316601-08d59ac2-5644-4404-a8c1-7f7e329b753d.png)

2023-02-12 14:38 UTC, Bishal011 commented
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/tusharkesarwani/reviewers)

2023-02-15 12:00 UTC, zugzwang03 approved these changes

2023-02-15 14:00 UTC, Vanshiii203 requested changes
Screenshot is not visible in the readme.

2023-02-15 15:05 UTC, Bishal011 commented on Projects/PIANO/Readme.md
> +![](Screenshot%20(214).png)
![Screenshot (214)](https://user-images.githubusercontent.com/105370000/219065799-3544f735-bbd5-445f-986f-5f29d16b7255.png)

2023-02-16 14:06 UTC, Bishal011 commented
Now please review this issue and merge the pull request.

2023-02-16 16:06 UTC, Vanshiii203 requested changes
Add the screenshot of project in readme

2023-02-17 05:50 UTC, Vanshiii203 approved these changes

2023-02-17 17:18 UTC, closed without merging

2023-02-17 17:19 UTC, TusharKesarwani commented
Copied project
https://codepen.io/gabrielcarol/pen/rGeEbY