Caesar Cipher
TusharKesarwani/Front-End-Projects pull request #658
Opened 2023-02-25 03:05 UTC by Harikaraja

## 🛠️ Issue (Number) : #654 

Closes #

# Description
Caesar Cipher is used to encode and decode the messages . We need to enter the the message in the text box also enter a key value and then click on encrypt button.
The message is encrypted to the user.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot (352)](https://user-images.githubusercontent.com/80022302/221332711-951712bd-d73d-4cf7-95c3-aab820ff2d0b.png)

2023-02-26 15:01 UTC, Anubhavgupta14 requested changes
@Harikaraja Your work is good but you need to improve the responsiveness of your website. Fix it then it will be merged.

2023-02-26 15:05 UTC, Harikaraja commented
Good evening sir ,

My code is failing time complexity..but I have done in c,c++ how can I
reduce the time complexity

On Sun, 26 Feb 2023, 20:31 Anubhav Gupta, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @Harikaraja <https://github.com/Harikaraja> Your work is good but you
> need to improve the responsiveness of your website. Fix it then it will be
> merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TusharKesarwani/Front-End-Projects/pull/658#pullrequestreview-1314684217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATCQWHU5RHYCZJMN3YW55ODWZNV5FANCNFSM6AAAAAAVHSHQOU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-26 16:04 UTC, Harikaraja commented
Sorry for the wrong reply sir ... I will work on responsiveness

On Sun, 26 Feb 2023, 20:34 Sri Harika, ***@***.***> wrote:

> Good evening sir ,
>
> My code is failing time complexity..but I have done in c,c++ how can I
> reduce the time complexity
>
> On Sun, 26 Feb 2023, 20:31 Anubhav Gupta, ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> @Harikaraja <https://github.com/Harikaraja> Your work is good but you
>> need to improve the responsiveness of your website. Fix it then it will be
>> merged.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/TusharKesarwani/Front-End-Projects/pull/658#pullrequestreview-1314684217>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATCQWHU5RHYCZJMN3YW55ODWZNV5FANCNFSM6AAAAAAVHSHQOU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***
>> com>
>>
>

2023-03-05 12:31 UTC, Vanshiii203 approved these changes

2023-03-08 05:02 UTC, harshit-paneri approved these changes

2023-03-08 05:14 UTC, harsh5902 approved these changes

2023-03-08 06:03 UTC, zugzwang03 approved these changes

2023-03-10 12:09 UTC, TusharKesarwani approved these changes

2023-03-10 12:10 UTC, merged