Voyage Slider Gsap
TusharKesarwani/Front-End-Projects pull request #706
Opened 2023-03-14 13:21 UTC by ashadmuneer

## 🛠️ Issue #676

Closes #676

# Description

he "voyage-slider-gsap" is a lightweight and customizable slider component that allows you to create responsive and touch-enabled sliders for your website or web application. It is built using HTML, CSS, and JavaScript

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://Voyage-Slider-Gsap.ashadmuneer.repl.co

2023-03-14 13:37 UTC, ashadmuneer commented
@Vanshiii203 Review this

2023-03-15 07:01 UTC, siddhi-244 requested changes
Add a readme file

2023-03-15 08:37 UTC, ashadmuneer commented
> Add a readme file

done

2023-03-15 09:11 UTC, zugzwang03 approved these changes

2023-03-16 11:18 UTC, merged